#!/usr/bin/env python3

#create file objects
file1 = open ('Biomart.tsv')
file2 = open ('ensGene.bed')

#read in the first file and make a dictionary
martDict = {}

for line in file1:
    fields = line.strip().split('\t')
    if len(fields) == 1:
        martDict[fields[0]] = ''
    else:
        martDict[fields[0]] = fields[1] 
        
        
#open the output file
outfile = open('G_species_MMM_YYYY_ensGene.bed', 'w')


#read in second file and make a dictionary
for line in file2:
    fields = line.strip().split('\t')
    # add the new field
    if fields[3] in martDict:
        line = '\t'.join(fields) + '\t' + martDict[fields[3]] + '\tNA'
    else:
        line = '\t'.join(fields) + '\t' + martDict[fields[1]] + '\tNA'
    
    
    #write to new file for use in IGB
    outfile.write(line + '\n')
